name: Deploy Application

on:
  push:
    branches: [teste-git-actions]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do projeto principal
      - name: Checkout Project Code
        uses: actions/checkout@v4

      # Checkout do código da arquitetura em outra pasta
      - name: Checkout Architecture Code
        uses: actions/checkout@v4
        with:
          repository: seriikmota/generic-architecture
          path: generic-architecture

      # Configuração do Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Build da arquitetura
      - name: Build Architecture
        run: |
          cd generic-architecture
          mvn clean install -DskipTests

      # Build do projeto principal
      - name: Build Project
        run: mvn clean install -DskipTests

      # Login no Docker Hub
      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker Image
        run: docker build -t piasisaulo/personal-system-backend .

      # Push da imagem Docker
      - name: Push Docker Image
        run: docker push piasisaulo/personal-system-backend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull piasisaulo/personal-system-backend:latest
      - name: Remove docker container
        run: docker rm -f deploy_personal
      - name: Run docker container
        run: docker run -d -p 8080:8080 \ -e DATABASE_USERNAME="postgres"\ -e DATABASE_PASSWORD="postgress "\ -e DATABASE_URL="jdbc:postgresql://database-1.cpmywiymsqir.eu-north-1.rds.amazonaws.com:5432/"\ --name deploy_personal piasisaulo/personal-system-backend